# Generated by Django 4.1 on 2024-08-28 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
